name: Hello Workflow

on: 
  issues:
    types: [opened, reopened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABEL: ${{ join(github.event.issue.labels.*.name, ', ') }}
          
        run: |
          echo "Issue Number: $ISSUE_NUMBER"
          echo "Issue Title: $ISSUE_TITLE"
          echo "Issue Body: $ISSUE_BODY"
          echo "Issue Assignees: $ISSUE_ASSIGNEES"
          echo "Issue Labels: $ISSUE_LABEL"


